version: '3.8'

services:
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: bussync-dev
      POSTGRES_USER: bussync
      POSTGRES_PASSWORD: bussync2024

volumes:
  postgres_data: