version: '3.8'

services:
#  web:
#    build: src/app
#    command: poetry run python manage.py runserver 0.0.0.0:8000
#    volumes:
#      - ./app/:/usr/src/app/
#    ports:
#      - 8000:8000
#    env_file:
#      - src/.env
#    depends_on:
#      - db
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    env_file:
      - .env
    environment:
      - POSTGRES_DB = bussync-dev
      - POSTGRES_PASSWORD = bussync2024
      - POSTGRES_USERNAME=bussync

volumes:
  postgres_data: